# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Sun Nov 18 05:32:34 PST 2012
#
#/ usage: ssh:add-authorized-key  --public-key <> [ --authorized-keys-file <$HOME/.ssh/authorized_keys>] [ --type <dsa>] [ --comment <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --public-key) rerun_option_check $# ; PUBLIC_KEY=$2 ; shift ;;
            --authorized-keys-file) rerun_option_check $# ; AUTHORIZED_KEYS_FILE=$2 ; shift ;;
            --type) rerun_option_check $# ; TYPE=$2 ; shift ;;
            --comment) rerun_option_check $# ; COMMENT=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$AUTHORIZED_KEYS_FILE" ] && AUTHORIZED_KEYS_FILE="$HOME/.ssh/authorized_keys"
    [ -z "$TYPE" ] && TYPE="dsa"
    # Check required options are set
    [ -z "$PUBLIC_KEY" ] && { echo >&2 "missing required option: --public-key" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
PUBLIC_KEY=
AUTHORIZED_KEYS_FILE=
TYPE=
COMMENT=


