# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Thu Nov 15 09:10:26 PST 2012
#
#/ usage: ssh:keygen [ --type <dsa>] [ --passphrase <>] [ --key-file <$HOME/.ssh/id_dsa>] [ --force <false>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --type) rerun_option_check $# ; TYPE=$2 ; shift ;;
            --passphrase) rerun_option_check $# ; PASSPHRASE=$2 ; shift ;;
            --key-file) rerun_option_check $# ; KEY_FILE=$2 ; shift ;;
            --force) rerun_option_check $# ; FORCE=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$TYPE" ] && TYPE="dsa"
    [ -z "$KEY_FILE" ] && KEY_FILE="$HOME/.ssh/id_dsa"
    [ -z "$FORCE" ] && FORCE="false"
    # Check required options are set

    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
TYPE=
PASSPHRASE=
KEY_FILE=
FORCE=


