# Generated by stubbs:add-option. Do not edit, if using stubbs.
# Created: Mon Dec  3 15:36:32 PST 2012
#
#/ usage: ssh:add-host-key  --hostname <> [ --type <dsa>] [ --known-hosts-file <$HOME/.ssh/known_hosts>] [ --host-key <>] 

# _rerun_options_parse_ - Parse the command arguments and set option variables.
#
#     rerun_options_parse "$@"
#
# Arguments:
#
# * the command options and their arguments
#
# Notes:
# 
# * Sets shell variables for any parsed options.
# * The "-?" help argument prints command usage and will exit 2.
# * Return 0 for successful option parse.
#
rerun_options_parse() {
    
    while [ "$#" -gt 0 ]; do
        OPT="$1"
        case "$OPT" in
            --hostname) rerun_option_check $# ; HOSTNAME=$2 ; shift ;;
            --type) rerun_option_check $# ; TYPE=$2 ; shift ;;
            --known-hosts-file) rerun_option_check $# ; KNOWN_HOSTS_FILE=$2 ; shift ;;
            --host-key) rerun_option_check $# ; HOST_KEY=$2 ; shift ;;
            # help option
            -?)
                rerun_option_usage
                exit 2
                ;;
            # end of options, just arguments left
            *)
              break
        esac
        shift
    done

    # Set defaultable options.
    [ -z "$TYPE" ] && TYPE="dsa"
    [ -z "$KNOWN_HOSTS_FILE" ] && KNOWN_HOSTS_FILE="$HOME/.ssh/known_hosts"
    # Check required options are set
    [ -z "$HOSTNAME" ] && { echo >&2 "missing required option: --hostname" ; return 2 ; }
    # If option variables are declared exportable, export them.

    #
    return 0
}


# Initialize the options variables to null.
HOSTNAME=
TYPE=
KNOWN_HOSTS_FILE=
HOST_KEY=


